### ISSUE TITLE
Table Issues (formatting and missing data)

### ISSUE THREAD

**Issue by cburrill** [NMGRL/pychron#2106] opened 2022-01-26 00:11 UTC
**Created a table using "Subgrouped Analyses" pipeline and ran into the following issues:**

1. The plateau information shows up in the area with the step heating analyses data (highlighted yellow in file)

2. The border line underneath the heating steps (row 18 in this case) no longer goes under all the columns but there is now a line that does goes under all columns above the notes. Preference would be to have only the line under the heating steps that appears under all columns, if possible.

3. In the Unknowns tab of the resulting spreadsheet, there is a column (BW) with header "(38Ar/38Ar)K" but I think it should be (38Ar/39Ar)K and the column is empty as well as the error column next to it. (outlined in red box in file)

**To Reproduce**
See screenshots of XLS options

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Most up-to-date version of PyCrunch (as of 1/25/22)

[MW-032-02.xlsx](https://github.com/NMGRL/pychron/files/7938053/MW-032-02.xlsx)
![XLS-options-main](https://user-images.githubusercontent.com/58988891/151080868-55497392-c4d3-4e1d-a5fc-8e3ab1c47f87.png)
![XLS-options-unknown](https://user-images.githubusercontent.com/58988891/151080870-624fb318-d3d6-4ac5-bca6-7e631b7139ee.png)

**Comment by jirhiker** [comment] 2022-01-26 00:14
k. thanks. those seem straightforward to fix

**Comment by jirhiker** [comment] 2022-01-26 16:06
1. I believe you made a subgrouped table (?). Therefore the display of the plateau information with the steps is by design. its showing the age for that subgroup.

**Comment by jirhiker** [comment] 2022-01-26 22:43
Great. Problem 3 should be addressed in the latest version

**Closed** 2022-02-01 16:45 UTC
Labels: Bug, Fixed, Tested OK, Data Presentation, Data Table
