### ISSUE TITLE
Adding unknown while running

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#737] opened 2016-03-15 18:37 UTC
PyExperiment crashed while adding an unknown using experiment editor during a current experiment.

```
Traceback (most recent call last):
  File "/Users/obama/Programming/git/pychron/pychron/core/ui/qt/gui.py", line 41, in event
    event.fn(*event.args, **event.kwargs)
  File "/Users/obama/Programming/git/pychron/pychron/experiment/factory.py", line 189, in _add_run
    is_run_block=rf.run_block_enabled)
  File "/Users/obama/Programming/git/pychron/pychron/experiment/queue/base_queue.py", line 181, in add_runs
    runs = self._add_runs(runspecs)
  File "/Users/obama/Programming/git/pychron/pychron/experiment/queue/base_queue.py", line 229, in _add_runs
    idx = aruns.index(self.selected[-1])
ValueError: <pychron.experiment.automated_run.spec.AutomatedRunSpec object at 0x12fdd6410> is not in list

```

**Comment by jirhiker** [comment] 2016-03-16 05:40
duplicate of #733

**Closed by jirhiker** 2016-03-16 05:40 UTC
Labels: Bug
