### ISSUE TITLE
error when selecting a project

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#911] opened 2016-08-17 22:25 UTC
active branch=release/v2.5

active analyses=

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/base_browser_model.py", line 627, in _selected_projects_changed
    self._load_associated_labnumbers()
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 42, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/base_browser_model.py", line 360, in _load_associated_labnumbers
    sams.extend(self._make_labnumbers())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 42, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/base_browser_model.py", line 420, in _make_labnumbers
    sams = self._load_sample_record_views(ls)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/base_browser_model.py", line 405, in _load_sample_record_views
    sams = progress_loader(lns, func, step=25)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 95, in progress_loader
    items = list(gen())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 86, in gen
    r = func(x, None, 0, 0)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/base_browser_model.py", line 403, in func
    return LabnumberRecordView(li)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/record_views.py", line 25, in __init__
    self._create(dbrecord)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/record_views.py", line 126, in _create
    sample = dbrecord.sample
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 583, in get
    value = self.callable_(state, passive)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 532, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 576, in _emit_lazyload
    return loading.load_on_ident(q, ident_key)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
    return q.one()
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2693, in one
    ret = list(self)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/connections.py", line 781, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/connections.py", line 942, in _read_query_result
    result.read()
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/connections.py", line 1138, in read
    first_packet = self.connection._read_packet()
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/connections.py", line 906, in _read_packet
    packet.check_error()
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/connections.py", line 367, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (pymysql.err.InternalError) (1054, u"Unknown column 'SampleTbl.note' in 'field list'") [SQL: u'SELECT `SampleTbl`.name AS `SampleTbl_name`, `SampleTbl`.id AS `SampleTbl_id`, `SampleTbl`.`materialID` AS `SampleTbl_materialID`, `SampleTbl`.`projectID` AS `SampleTbl_projectID`, `SampleTbl`.note AS `SampleTbl_note` \nFROM `SampleTbl` \nWHERE `SampleTbl`.id = %s'] [parameters: (12,)]

```

**Comment by jirhiker** [comment] 2016-08-17 22:36
duplicate of #910

**Closed** 2016-08-17 22:36 UTC
Labels: Bug
